### ISSUE TITLE
Two Mistakes in the Processed Dataset

### ISSUE THREAD

**Issue by yuzhTHU** [DynamicaLab/data-dynalearn#2]
Hello, authors. Thanks for your excellent work and the opened dataset! However, I found two issues in your processed dataset, and I believe that they are mistakes.

1. It seems that you mistake the `processed-dataset/case-timeseries.data` as the `processed-dataset/population.data`. (It‘s a little bug that doesn't matter)
2. **The population data, time-series data (i.e., COVID-19 data), and mobility data do not match each other.** (I believe it's a fatal bug)

Let me explain the second issue in more detail: 

According to the [Document](https://cnecovid.isciii.es/covid19/resources/metadata_casos_hosp_uci_def_sexo_edad_provres.pdf) provided on [https://cnecovid.isciii.es/covid19/#documentaci%C3%B3n-y-datos](https://cnecovid.isciii.es/covid19/#documentaci%C3%B3n-y-datos), the 'NC' term in the `provincia_iso` column of `cases-data.csv` means "no consta" (i.e., not included/provided). 

However, the pycountry library mistakes it for the `Subdivision(code='ES-NC', country_code='ES', name='Nafarroako Foru Komunitatea*', parent_code=None, type='Autonomous community')`. That's why your `name_map` has 53 items rather than 52. 

Therefore, when you dump the `timeseries` into the file `f"{path_to_processed}/case-timeseries.data"`, you actually keep the `NC` term and drop the final `ZA` term (i.e., the Zamora province). So the `timeseries` data does not match with 'population' data (and the mobility data as well).

Thanks for your excellent work again! If there is anything I have mistaken or misunderstood, please let me know.

**Comment by antoineallard** [comment]
Thank you for the feedback. The lead author @charlesmurphy1 will decide on the best way to move forward.

**Comment by charlesmurphy1** [comment]
Thanks for pointing this out! The data processing notebook has been refactored accordingly. Everything should be fine now.

**Comment by charlesmurphy1** [comment]
Thanks for pointing this out! The data processing notebook has been modified and refactored accordingly. Everything should be fine now.
